# Generated by Django 4.1.4 on 2023-02-28 10:07

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_pic', models.ImageField(default='', upload_to='')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_no', models.CharField(max_length=12)),
                ('aadhar', models.ImageField(default='', upload_to='')),
                ('aadhar_status', models.BooleanField(default=False)),
                ('pan', models.ImageField(default='', upload_to='')),
                ('pan_status', models.BooleanField(default=False)),
                ('cheque', models.ImageField(default='', upload_to='')),
                ('cheque_status', models.BooleanField(default=False)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'User')], default=2, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('tc', models.BooleanField(default=False)),
                ('otp', models.CharField(max_length=6)),
                ('refer_code', models.CharField(blank=True, max_length=8, null=True)),
                ('commission_status', models.BooleanField(default=False)),
                ('user_created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('user_modified_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercredit_User_created_by', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercredit_User_modified_by', to=settings.AUTH_USER_MODEL)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercredit_User_referred_by', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_bank_name', models.CharField(max_length=100)),
                ('card_type', models.CharField(max_length=20)),
                ('card_network', models.CharField(max_length=50)),
                ('card_number', models.PositiveBigIntegerField(unique=True)),
                ('card_holder_name', models.CharField(max_length=100)),
                ('card_photo', models.CharField(max_length=100)),
                ('card_exp_date', models.DateField()),
                ('card_cvv', models.IntegerField()),
                ('due_date', models.DateField()),
                ('commission', models.FloatField(blank=True, default=2.0, null=True, validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(100)])),
                ('due_amount', models.FloatField(default=0)),
                ('card_status', models.BooleanField(default=False)),
                ('commission_total_amount', models.FloatField(blank=True, null=True)),
                ('commission_paid_through', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_user', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_user', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_paid_through', models.CharField(max_length=100)),
                ('amount_paid', models.FloatField(default=0)),
                ('commission', models.FloatField(blank=True, default=2.0, null=True, validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(100)])),
                ('profit_amount', models.FloatField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(default=datetime.datetime.now)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_id', to=settings.AUTH_USER_MODEL)),
                ('card_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_card_id', to='usercredit.card')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_holder_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
