# Generated by Django 4.1.4 on 2022-12-28 04:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_no', models.CharField(max_length=12)),
                ('aadhar', models.ImageField(default='', upload_to='uploads/Aadhar/')),
                ('aadhar_status', models.BooleanField(default=False)),
                ('pan', models.ImageField(default='', upload_to='uploads/pan/')),
                ('pan_status', models.BooleanField(default=False)),
                ('cheque', models.ImageField(default='', upload_to='uploads/cheque/')),
                ('cheque_status', models.BooleanField(default=False)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'User')], default=2, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('tc', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('commission_status', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercredit_User_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercredit_User_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_bank_name', models.CharField(max_length=100)),
                ('card_type', models.CharField(choices=[('business', 'BUSINESS'), ('personal', 'PERSONAL')], max_length=15)),
                ('card_number', models.PositiveBigIntegerField(unique=True)),
                ('card_holder_name', models.CharField(max_length=100)),
                ('card_photo', models.CharField(max_length=100)),
                ('card_exp_date', models.DateField()),
                ('card_cvv', models.IntegerField()),
                ('due_date', models.DateField()),
                ('commission', models.FloatField(editable=False, validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(100)])),
                ('due_amount', models.BigIntegerField()),
                ('card_status', models.BooleanField(default=False)),
                ('commission_total_amount', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_user', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paid_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_by_user', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
