# Generated by Django 4.1.4 on 2023-02-28 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='under_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercredit_User_under_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
