# Generated by Django 4.1.4 on 2023-03-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_category',
            field=models.CharField(default='debit', max_length=20),
            preserve_default=False,
        ),
    ]
