# Generated by Django 4.1.4 on 2023-04-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0002_card_card_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='Images\\Profile_pic'),
        ),
    ]
