# Generated by Django 4.1.4 on 2023-03-02 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0002_user_under_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='admin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
