# Generated by Django 4.1.4 on 2022-12-28 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0003_alter_card_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='commission',
            field=models.FloatField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
