# Generated by Django 4.1.4 on 2023-04-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0004_card_credit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='available_balance',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='credit_amount',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
