# Generated by Django 4.1.4 on 2023-03-02 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0004_alter_transaction_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user_id',
            new_name='card_holder_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='card_id',
            new_name='card_object_id',
        ),
    ]
