# Generated by Django 4.1.4 on 2022-12-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0004_alter_card_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='commission_total_amount',
            field=models.BigIntegerField(blank=True, default=30),
            preserve_default=False,
        ),
    ]
