# Generated by Django 4.1.4 on 2023-03-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0005_rename_user_id_transaction_card_holder_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='card_holder_id',
        ),
    ]
