# Generated by Django 4.1.4 on 2023-04-17 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0006_rename_commission_total_amount_card_profit_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='due_paid_at',
        ),
        migrations.RemoveField(
            model_name='card',
            name='due_paid_through',
        ),
        migrations.RemoveField(
            model_name='card',
            name='paid_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='due_paid_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='due_paid_through',
            field=models.CharField(default='Google pay', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='paid_amount',
            field=models.FloatField(default=0),
        ),
    ]
