# Generated by Django 4.1.4 on 2023-03-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0006_remove_transaction_card_holder_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='admin_id',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='card_object_id',
            new_name='card',
        ),
    ]
