# Generated by Django 4.1.4 on 2022-12-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0006_alter_card_commission_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='due_amount',
            field=models.FloatField(),
        ),
    ]
