# Generated by Django 4.1.4 on 2022-12-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0007_alter_card_due_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='commission',
            field=models.FloatField(blank=True),
        ),
    ]
