# Generated by Django 4.1.4 on 2023-04-18 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0008_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='due_paid_at',
        ),
        migrations.AddField(
            model_name='transaction',
            name='due_paid_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='transaction',
            name='due_paid_time',
            field=models.TimeField(auto_now_add=True, default='16:59:00'),
            preserve_default=False,
        ),
    ]
