# Generated by Django 4.1.4 on 2023-01-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0009_alter_card_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='commission_total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
