# Generated by Django 4.1.4 on 2023-04-20 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0010_alter_transaction_due_paid_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='due_paid_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='due_paid_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
