# Generated by Django 4.1.4 on 2023-01-02 04:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0010_alter_card_commission_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='commission',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
