# Generated by Django 4.1.4 on 2023-01-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0011_alter_card_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='due_amount',
            field=models.FloatField(default=0),
        ),
    ]
