# Generated by Django 4.1.4 on 2023-04-26 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0012_alter_card_card_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='due_paid_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='due_paid_time',
        ),
        migrations.AddField(
            model_name='card',
            name='payment_method',
            field=models.CharField(default='Cycle', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='due_paid_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(default='Partial', max_length=30),
            preserve_default=False,
        ),
    ]
