# Generated by Django 4.1.4 on 2023-01-10 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0012_alter_card_due_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refer_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercredit_User_referred_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
