# Generated by Django 4.1.4 on 2023-04-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0013_remove_transaction_due_paid_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='charges',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
