# Generated by Django 4.1.4 on 2023-01-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0013_user_refer_code_user_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='commission_total_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='%.2f'),
        ),
    ]
