# Generated by Django 4.1.4 on 2023-01-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0015_alter_card_commission_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refer_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
