# Generated by Django 4.1.4 on 2023-01-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0016_alter_user_refer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-16 12:34:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
