# Generated by Django 4.1.4 on 2023-04-27 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0017_payment_request_admin_payment_request_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_request',
            old_name='created_at',
            new_name='requested_at',
        ),
        migrations.AddField(
            model_name='payment_request',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
