# Generated by Django 4.1.4 on 2023-01-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0017_user_user_created_at_user_user_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_created_at',
            field=models.DateTimeField(),
        ),
    ]
