# Generated by Django 4.1.4 on 2023-01-17 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0018_alter_user_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
