# Generated by Django 4.1.4 on 2023-01-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0019_alter_user_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_modified_at',
            field=models.DateTimeField(),
        ),
    ]
