# Generated by Django 4.1.4 on 2023-04-27 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0019_remove_card_card_status_remove_card_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='due_amount',
        ),
        migrations.RemoveField(
            model_name='card',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='commission',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
