# Generated by Django 4.1.4 on 2023-01-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0020_alter_user_user_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_modified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
