# Generated by Django 4.1.4 on 2023-04-27 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0020_remove_card_due_amount_remove_card_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_request_id', to='usercredit.payment_request'),
        ),
    ]
