# Generated by Django 4.1.4 on 2023-01-17 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0022_alter_user_user_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
