# Generated by Django 4.1.4 on 2023-04-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0022_remove_payment_request_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='payment_request',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
