# Generated by Django 4.1.4 on 2023-01-17 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0023_alter_user_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_modified_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
