# Generated by Django 4.1.4 on 2023-04-28 04:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0023_remove_transaction_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='commission',
            field=models.FloatField(blank=True, default=2.0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='commission',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
