# Generated by Django 4.1.4 on 2023-01-17 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0024_alter_user_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='card',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
