# Generated by Django 4.1.4 on 2023-04-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0024_alter_card_commission_alter_transaction_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='profit_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='profit_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
