# Generated by Django 4.1.4 on 2023-05-04 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0025_remove_card_profit_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='commission',
            new_name='profit',
        ),
    ]
