# Generated by Django 4.1.4 on 2023-01-18 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0026_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
