# Generated by Django 4.1.4 on 2023-05-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0028_transaction_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_request',
            name='cycle_deposit_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment_request',
            name='cycle_withdraw_status',
            field=models.BooleanField(default=False),
        ),
    ]
