# Generated by Django 4.1.4 on 2023-01-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0028_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar',
            field=models.ImageField(default='', upload_to='static/Aadhar/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cheque',
            field=models.ImageField(default='', upload_to='static/cheque/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pan',
            field=models.ImageField(default='', upload_to='static/pan/'),
        ),
    ]
