# Generated by Django 4.1.4 on 2023-05-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0029_payment_request_cycle_deposit_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_request',
            name='payment_method_flag',
            field=models.CharField(default='Cycle Deposit', max_length=25),
            preserve_default=False,
        ),
    ]
