# Generated by Django 4.1.4 on 2023-01-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0029_alter_user_aadhar_alter_user_cheque_alter_user_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar',
            field=models.ImageField(default='', upload_to='Final Credit/creditmanagement/usercredit/Images/Aadhar'),
        ),
    ]
