# Generated by Django 4.1.4 on 2023-05-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0030_payment_request_payment_method_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_request',
            name='payment_method_flag',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
