# Generated by Django 4.1.4 on 2023-05-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0031_alter_payment_request_payment_method_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_request',
            name='payment_method_flag',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method_flag',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
