# Generated by Django 4.1.4 on 2023-01-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0031_alter_user_aadhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cheque',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='pan',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
