# Generated by Django 4.1.4 on 2023-01-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0032_alter_user_cheque_alter_user_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='commission_paid_through',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
