# Generated by Django 4.1.4 on 2023-05-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0032_remove_payment_request_payment_method_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method_flag',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
