# Generated by Django 4.1.4 on 2023-05-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0035_remove_card_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='withdraw_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
