# Generated by Django 4.1.4 on 2023-02-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0035_alter_card_created_by_alter_card_paid_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
