# Generated by Django 4.1.4 on 2023-05-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0036_transaction_withdraw_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pdf',
            field=models.FileField(default='', upload_to='Pdf/UserRecord'),
        ),
    ]
