# Generated by Django 4.1.4 on 2023-05-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0036_transaction_withdraw_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='media',
            field=models.FileField(default='', upload_to='Video\\sample_video'),
        ),
    ]
