# Generated by Django 4.1.4 on 2023-05-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0037_user_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='media',
        ),
    ]
