# Generated by Django 4.1.4 on 2023-05-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0037_transaction_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='pdf',
            field=models.FileField(default='', upload_to='Pdf/UserPdf'),
        ),
    ]
