# Generated by Django 4.1.4 on 2023-06-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0038_alter_transaction_pdf'),
        ('usercredit', '0038_remove_user_media'),
    ]

    operations = [
    ]
