# Generated by Django 4.1.4 on 2023-06-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0039_merge_20230602_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='profit_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='withdraw_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
