# Generated by Django 4.1.4 on 2023-06-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercredit', '0040_alter_transaction_profit_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='pdf',
        ),
    ]
